### ISSUE TITLE
Semibin fully impleneted in Dev branch?

### ISSUE THREAD

**Issue by julianzaugg** [rhysnewell/aviary#45]
I see that you have added [Semibin](https://github.com/BigDataBiology/SemiBin) to the dev branch. Is this fully implemented yet?

The output does not appear to be processed by `rule das_tool` and downstream steps?

**Comment by rhysnewell** [comment]
I don't want to include SemiBin in aviary as training a new model for novel samples takes way too long, it would severely impede people's pipelines. You also can't use any of their pregenerated models when you have more than one sample, so it's pretty much a requirement that you train a new model each time you want to use it.

I've only put it in aviary for benchmarking purposes as I need to benchmark it against rosella.

**Comment by julianzaugg** [comment]
Ok thanks for confirming that.

**Comment by StevenJRobbins** [comment]
Hey Rhys. Thanks for commenting on this. When you say that you can only use the pretrain model if you have just one sample, do you mean for differential coverage? That is, you're saying that you can only use a pretrain model (e.g. Global) if you input one assembly, one file for read mapping? But if you wanted to input several read files for diff coverage, that wouldn't be allowed using a pretrain model.

**Comment by rhysnewell** [comment]
Yeah, exactly

**Comment by StevenJRobbins** [comment]
Well that's not nearly as friendly as you'd like, unless you just ran it single-sample even if more than one is provided. Bummer. Anyway, thanks!

**Comment by rhysnewell** [comment]
In the readme on their GitHub, they show this line: 
```
SemiBin single_easy_bin -i contig.fa -b *.bam -o output --environment human_gut
```
Which implies you can use multiple BAM files with a model selected. However, using the exact same setup on the CAMI benchmark metagenomes that contain multiple samples this command will throw an error indicating you can't use the a pretrained model with multiple BAM files. This is my experience, happy to proven wrong on this but this is how it has worked from my testing

**Comment by StevenJRobbins** [comment]
I emailed the developer(s) and got this reply:

Dev 1:
"Yes, from our design of the algorithm used in SemiBin, we only provide the pretrained model for the single-sample binning. When using multiple samples, you need to train the model for your data."

Dev 2:
"I think this was a typo in the README file, which was reported (I assume by your collaborator) and Shaojun has fixed

It is actually a bit unfortunate that we cannot perform multi-sample mode with pretrained models but it's not easy to adapt the system. You can always run in single-sample mode, which will be very fast."

Only way to do it at speed would be to do single sample binning using a single set of reads as input--e.g. only the nanopore file, a user specified file, or just first read file read in. Global would still work for most things, and for specific environments, it could make a significant improvement. For my part though, it's a low priority request, not suggesting it's critical.

**Comment by rhysnewell** [comment]
Yeah, I already talked to them about this. I'm not really sure it is worth it at this stage. As I said before, I'm having to rerun a bunch of benchmarks so if turns out that semibin does provide significant improvements then maybe later on I'll add an option for it. I don't think running it with only one sample would be too good, so I'm gonna avoid doing that.

**Comment by StevenJRobbins** [comment]
Sounds reasonable. 😊

Steven Robbins, PhD
Postdoctoral researcher
Australian Centre for Ecogenomics
L5/76 MBS Bldg
University of Queensland
http://ecogenomic.org/personnel/dr-steven-robbins


From: Rhys Newell ***@***.***>
Date: Monday, 16 May 2022 at 1:47 pm
To: rhysnewell/aviary ***@***.***>
Cc: Mr Steven Robbins ***@***.***>, Comment ***@***.***>
Subject: Re: [rhysnewell/aviary] Semibin fully impleneted in Dev branch? (Issue #45)

Yeah, I already talked to them about this. I'm not really sure it is worth it at this stage. As I said before, I'm having to rerun a bunch of benchmarks so if turns out that semibin does provide significant improvements then maybe later on I'll add an option for it. I don't think running it with only one sample would be too good, so I'm gonna avoid doing that.
