### ISSUE TITLE
Flye seems to assemble long reads as '--pacbio-raw' despite '--long_read_type ont' being specified

### ISSUE THREAD

**Issue by chklovski** [rhysnewell/aviary#87]
Hi,

After assembling a combined nanopore/short read assembly with aviary assemble (v 0.5.6) and using the "--long_read_type ont" flag, the completed flye log in the aviary /data/flye/ folder shows the long reads being passed to flye as pacbio reads:

`DEBUG: Cmd: ../bin/flye --pacbio-raw data/long_reads.fastq.gz --meta -o data/flye -t 60`

Is aviary assembling nanopore reads as pacbio reads?

**Comment by rhysnewell** [comment]
It shouldn't be: https://github.com/rhysnewell/aviary/blob/main/aviary/modules/assembly/scripts/run_flye.pyhttps://github.com/rhysnewell/aviary/blob/main/aviary/modules/assembly/scripts/run_flye.py

Could you post the `config.yaml` file that is getting produced and the full command you use? The long read type might be getting improperly set

**Comment by rhysnewell** [comment]
Checking recent runs from aviary using flye, the correct Flye model is used: `[2022-08-29 18:55:55] root: DEBUG: Cmd: /home/n10853499/.conda/envs/c3c0686c893ff8bc62570d7e007b47c9/bin/flye --nano-raw data/long_reads.fastq.gz --meta -o data/flye -t 28`

So I'll need some extra details

**Comment by chklovski** [comment]
I've emailed you the logs. It also is reproducible by other people from a central conda environment, so it doesn't seem to be just an issue on my end.

**Comment by rhysnewell** [comment]
Cool got it, and figured it out. For some reason the central conda environment version of aviary is now writing the long_read_type parameter to the `yaml` file as a list:
```
long_reads:
- /mnt/hpccs01/scratch/microbiome/n10851381/peter_recurm_reads_round2/all_reads/sample1.long.combined.renamed.fastq.gz
long_read_type:
- ont
```

When it should be writing it as a single value i.e.
```
long_reads:
- /mnt/hpccs01/scratch/microbiome/n10851381/peter_recurm_reads_round2/all_reads/sample1.long.combined.renamed.fastq.gz
long_read_type: ont
```

I'm assuming this is due to some dependency updating in the background as this seems like a fairly recent issue. I'm not sure how different the pacbio-raw and nano-raw models of Flye are, so hopefully not much damage has been done.

I'll push a fix in a minute

**Comment by rhysnewell** [comment]
Fixed in main branch
